
version: "3"

services:
  gitlab-runner:
    container_name: gitlab-runner
    image: hccorigin/gitlab-runner:17.4.1
#    platform: linux/amd64
    privileged: true
    restart: always
    hostname: runner
    environment:
      - TZ=Asia/Seoul
    working_dir: /prod/gitlab-runner
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        groupdel docker
        groupadd docker --gid 1001
        useradd -g docker docker --uid 1001 -d /prod/gitlab-runner
        /usr/bin/dumb-init /entrypoint run --user=docker --working-directory=/prod/gitlab-runner
    extra_hosts:
      - "xxx.example.com:xxx.xxx.xxx.xxx"
    volume:
      - $PWD:/prod/gitlab-runner
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

#networks:
#  default:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: xxx.xxx.xxx.xxx/xx
#          gateway: xxx.xxx.xxx.1
